---
- name: update homebrew
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true

- name: install taps
  community.general.homebrew_tap:
    name: "{{ taps }}"

- name: install casks
  community.general.homebrew_cask:
    name: "{{ casks }}"
    install_options: cask
    state: present

- name: install packages
  community.general.homebrew:
    name: "{{ packages }}"
    state: present
