---
- name: add asdf java plugin
  ansible.builtin.command:
    chdir: "{{ lookup('env', 'HOME') }}"
    cmd: asdf plugin-add java https://github.com/halcyon/asdf-java.git
    creates: "{{ lookup('env', 'HOME') }}/.asdf/plugins/java/README.md"

- name: add asdf python plugin
  ansible.builtin.command:
    chdir: "{{ lookup('env', 'HOME') }}"
    cmd: asdf plugin-add python https://github.com/asdf-community/asdf-python.git
    creates: "{{ lookup('env', 'HOME') }}/.asdf/plugins/python/README.md"

- name: install java versions
  with_items:
    - 17
    - 21
  ansible.builtin.command:
    chdir: "{{ lookup('env', 'HOME') }}"
    cmd: asdf install java latest:temurin-{{ item }}
    creates: "{{ lookup('env', 'HOME') }}/.asdf/installs/java/temurin-{{ item }}/release"

- name: asdf global java version 21
  ansible.builtin.command:
    chdir: "{{ lookup('env', 'HOME') }}"
    cmd: asdf global java latest:temurin-21

- name: install python versions
  with_items:
    - 3.12.2
  ansible.builtin.command:
    chdir: "{{ lookup('env', 'HOME') }}"
    cmd: "asdf install python {{ item }}"
    creates: "{{ lookup('env', 'HOME') }}.asdf/installs/python/{{ item }}"

- name: asdf global python version 3.12.2
  ansible.builtin.command:
    chdir: "{{ lookup('env', 'HOME') }}"
    cmd: asdf install python 3.12.2

- name: copy dotfile
  ansible.builtin.copy:
    src: "files/.asdfrc"
    dest: "{{ lookup('env', 'HOME') }}/.asdfrc"
