---
- name: ensure .config directories exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/nvim/lua/carefulnow/plugins"
    recurse: true
    state: directory

- name: copy configuration files
  with_items:
    - .config/nvim/init.lua
    - .config/nvim/lua/carefulnow/init.lua
    - .config/nvim/lua/carefulnow/autocmd.lua
    - .config/nvim/lua/carefulnow/global.lua
    - .config/nvim/lua/carefulnow/keymap.lua
    - .config/nvim/lua/carefulnow/lazy.lua
    - .config/nvim/lua/carefulnow/set.lua
    - .config/nvim/lua/carefulnow/plugins/code-stats.lua
    - .config/nvim/lua/carefulnow/plugins/diffview.lua
    - .config/nvim/lua/carefulnow/plugins/gitsigns.lua
    - .config/nvim/lua/carefulnow/plugins/lsp-zero.lua
    - .config/nvim/lua/carefulnow/plugins/neo-tree.lua
    - .config/nvim/lua/carefulnow/plugins/telescope.lua
    - .config/nvim/lua/carefulnow/plugins/todo-comments.lua
    - .config/nvim/lua/carefulnow/plugins/tokyonight.lua
    - .config/nvim/lua/carefulnow/plugins/undotree.lua
    - .config/nvim/lua/carefulnow/plugins/vim-markdown-toc.lua
    - .config/nvim/lua/carefulnow/plugins/which-key.lua

  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/{{ item }}"

- name: setup nvim with configuration
  ansible.builtin.command:
    chdir: "{{ lookup('env', 'HOME') }}"
    cmd: nvim --headless "+Lazy! sync" +qa

